### ISSUE TITLE
Clickatell Integration outdated

### ISSUE THREAD

**Issue by zAlwaysTheSun** [humhub-contrib/sms#15]
Hello,
I allow myself to open an "issue" because the Clickatell API has changed after 7 years, and the request form has changed.
I'll make a pull request as soon as I fix the problem.
Have a good day.

**Comment by zAlwaysTheSun** [comment]
Sorry, i don't know how to include 2 files in 1 pull request, I'm new on GitHub.

**Comment by luke-** [comment]
Thanks for you contribution! Is your change finished? If so, we could release a new version of the module.

**Comment by zAlwaysTheSun** [comment]
> Thanks for you contribution! Is your change finished? If so, we could release a new version of the module.

I'll take a closer look tomorrow!  It was a pleasure to contribute to the module!

**Comment by zAlwaysTheSun** [comment]
I just looked, that's all there was to change. I plan to add suppliers to the module in the future, you can count on me.
Have a good day ! :D

**Comment by luke-** [comment]
@zAlwaysTheSun Nice to hear! :-) A SMS driver could possibly also be something for the two-factor module.
https://github.com/humhub/twofa

Just released 0.7.6
https://github.com/humhub-contrib/sms/releases/tag/v0.7.6
