### ISSUE TITLE
Synchronization between marketplace and GitHub

### ISSUE THREAD

**Issue by matthiez** [humhub-contrib/sms#7]
Hi,
a few weeks ago #6 got merged into master.
I am using it locally just fine but will it be updated in the marketplace at some point too?
Or is it because I didn't bump the version?

Thank you!

**Comment by luke-** [comment]
I've just released v0.7.2 with your enhancements.
https://github.com/humhub-contrib/sms/releases/tag/v0.7.2

Thank you!
